name: Auto Create PR from Dev to Main

on:
  push:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Run build
        run: npm run build
  create-pr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: main
          pr_title: "Auto PR: Merge dev into main"
          pr_body: |
            This is an automated pull request created when changes were pushed to the `dev` branch.
            
            ## Changes
            Please review the changes and merge when ready.
            
            **Note:** This PR was automatically created by GitHub Actions.
          github_token: ${{ secrets.GITHUB_TOKEN }} 