name: Auto Create PR from Dev to Main

on:
  push:
    branches: [dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
        env:
          MONGOLINK: ${{ secrets.MONGOLINK }}
          MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
  create-pr:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate PR token
        env:
          PR_CREATOR_TOKEN: ${{ secrets.PR_CREATOR_TOKEN }}
        run: |
          if [ -z "$PR_CREATOR_TOKEN" ]; then
            echo "::error::Missing PR_CREATOR_TOKEN secret. Add a fine-grained PAT with Pull requests: Read/Write and Contents: Read."
            exit 1
          fi

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PR_CREATOR_TOKEN }}
        with:
          source_branch: dev
          destination_branch: main
          pr_title: "Auto PR: Merge dev into main"
          pr_body: |
            This is an automated pull request created when changes were pushed to the `dev` branch.

            ## Changes
            Please review the changes and merge when ready.

            **Note:** This PR was automatically created by GitHub Actions.
          github_token: ${{ secrets.PR_CREATOR_TOKEN }}
